### ISSUE TITLE
WMDL to OBJ support

### ISSUE THREAD

**Issue by sandpail** [Olivercomet/MorcuTool#7]
I'm not sure if you're still working on this tool, but i've noticed that it's possible to convert RevoModel files to .obj but not WindowsModel to .obj. 
![image](https://github.com/Olivercomet/MorcuTool/assets/168058098/2f14389f-dcf3-4b95-9812-e0371afe8a7a)
The behavior for exporting .rmdl is as follows:
![image](https://github.com/Olivercomet/MorcuTool/assets/168058098/e77d00b1-ef66-4204-97da-6ccec54beaee)
The tool has been great for my resource pack, and I'm very grateful for the hard work!  Texture, material and clip files are exportable, this is the only issue I can't find a workaround for. I have very little programming skill especially regarding c#, so I don't know how to convert the format's face/vertex information into obj automatically.

**EDIT:** I had just checked the other issues, this is apparently not a supported feature, so my post is moreso a suggestion than a bug. Despite that, i noticed in the source that both WMDL and RMDL have functions for obj generation, and they are surprisingly different. Since it's unimplemented, does the WMDL conversion work in the state that it's in presently?

**Comment by Olivercomet** [comment]
Try the new release?

**Comment by sandpail** [comment]
> Try the new release?

That was the fix, thank you!
